# name: MarkTangBlog

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3
#         with:
#           persist-credentials: false

#       - name: Install and Build
#         run: |
#           npm install
#           npm run build

#       - name: MarkTangBlog
#         uses: peaceiris/actions-gh-pages@v3
#         with:
#           github_token: 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
#           publish_dir: ./docs/.vitepress/dist

name: Build and Deploy to gh-pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Configure Git
        run: |
          git config --global user.name "MarkTang3611"
          git config --global user.email "marktang3611@qq.com"

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: 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
          publish_dir: ./docs/.vitepress/dist
          force_orphan: true
